version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - /
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - "*eslint*"
      vite:
        patterns:
          - "@vitejs/*"
          - "vite"
      vitest:
        patterns:
          - "vitest"
    ignore:
      - dependency-name: "@types/*"
      - dependency-name: "lodash"
      - dependency-name: "react"
      - dependency-name: "*react-dom"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
