version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - /
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - "*eslint*"
      vite:
        patterns:
          - "@vitejs/*"
          - "vite"
      vitest:
        patterns:
          - "vitest"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
    ignore:
      - dependency-name: "lodash"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
