version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - /

    schedule:
      interval: "daily"

    commit-message:
      prefix: "📦 "
      include: scope
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

    versioning-strategy: increase

    allow:
      - dependency-type: "direct"

    groups:
      ESLint:
        applies-to: version-updates
        patterns:
          - "*eslint*"
        update-types:
          - minor
          - patch
      Vite:
        patterns:
          - "@vitejs/*"
          - "vite"
        update-types:
          - minor
          - patch
      Vitest:
        patterns:
          - "vitest"
        update-types:
          - minor
          - patch
      React:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - minor
          - patch

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
